# Generated by Django 5.2.4 on 2025-08-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resident',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resident',
            name='tribe',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
