# Generated by Django 5.2.4 on 2025-08-18 10:20

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_resident_place_of_birth_resident_religion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='nida_number',
            field=models.CharField(max_length=20, unique=True, validators=[utils.validators.validate_nida_number]),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[utils.validators.validate_phone_number]),
        ),
    ]
